export * from './IJob'
export * from './IPostulant'
export * from './IPersona'
export * from './IUser'
export * from './IRol'
export * from './IGrado'
export * from './IEstado'
export * from './IConvocatoriaPostulante'